global:
  scrape_interval: 30s
  evaluation_interval: 1m

scrape_configs:
    - job_name: 'prometheus'
      static_configs:
        - targets: [10.90.111.111:9090] 

    - job_name: 'postgres_linux'
      static_configs:
        - targets: ['postgres-exporter-Linux:9187'] 

    - job_name: 'postgres_windows'
      static_configs:
        - targets: ['postgres-exporter-Windows:9188'] 